---
-
  name: "Agustín de Zárate's Description of Gonzalo Pizarro's Expedition to locate the Land of Cinnamon and to find the Land of El Dorado"
  shortname: "zarate"
  galleries:
    -
      name: "Agustín de Zárate's Description of Gonzalo Pizarro's Expedition to locate the Land of Cinnamon and to find the Land of El Dorado"
      shortname: "El Dorado"
      path: "zarate"
      filename: "zarate.yaml"
      label-prefix: "Z"
      images_per_row: 3
-
  name: "John Hemming's Description of Gonzalo Pizarro's Expedition to locate the Lands of Cinnamon and of El Dorado"
  shortname: "hemming"
  galleries:
    -
      name: "John Hemming's Description of Gonzalo Pizarro's Expedition to locate the Lands of Cinnamon and of El Dorado"
      shortname: "El Dorado"
      path: "hemming"
      filename: "hemming.yaml"
      label-prefix: "H"
      images_per_row: 3
-
  name: "William H. Prescott's Portrait of Gonzalo Pizarro."
  shortname: "gonzalo_prescott"
  galleries:
    -
      name: "William H. Prescott's Portrait of Gonzalo Pizarro."
      shortname: "Gonzalo Prescott"
      path: "gonzalo_prescott"
      filename: "gonzalo_prescott.yaml"
      label-prefix: "G"
      images_per_row: 3
