---
-
  name: "Agustín de Zárate's Description of Gonzalo Pizarro's Expedition to locate the Land of Cinnamon and to find the Land of El Dorado"
  shortname: "zarate"
  galleries:
    -
      name: "Agustín de Zárate's Description of Gonzalo Pizarro's Expedition to locate the Land of Cinnamon and to find the Land of El Dorado"
      shortname: "El Dorado"
      path: "zarate"
      filename: "zarate.yaml"
      label-prefix: "Z"
      images_per_row: 3
-
  name: "John Hemming's Description of Gonzalo Pizarro's Expedition to locate the Lands of Cinnamon and of El Dorado"
  shortname: "hemming"
  galleries:
    -
      name: "John Hemming's Description of Gonzalo Pizarro's Expedition to locate the Lands of Cinnamon and of El Dorado"
      shortname: "El Dorado"
      path: "hemming"
      filename: "hemming.yaml"
      label-prefix: "H"
      images_per_row: 3
-
  name: "William H. Prescott's Portrait of Gonzalo Pizarro."
  shortname: "gonzalo_prescott"
  galleries:
    -
      name: "William H. Prescott's Portrait of Gonzalo Pizarro."
      shortname: "Gonzalo Prescott"
      path: "gonzalo_prescott"
      filename: "gonzalo_prescott.yaml"
      label-prefix: "G"
      images_per_row: 3
-
  name: "A portrait of Francisco de Orellana by Jos&eacute; Toribio Medina (1934)."
  shortname: "orellana_medina"
  galleries:
    -
      name: "A portrait of Francisco de Orellana by Jos&eacute; Toribio Medina (1934)."
      shortname: "Orellana Medina"
      path: "orellana_medina"
      filename: "orellana_medina.yaml"
      label-prefix: "O"
      images_per_row: 3
-
  name: "The names of the men on the voyage of discovery down the Amazon, from \"The Discovery of the Amazon\", by Jos&eacute; Toribio Medina."
  shortname: "names"
  galleries:
    -
      name: "The names of the men on the voyage of discovery down the Amazon, from \"The Discovery of the Amazon\", by Jos&eacute; Toribio Medina."
      shortname: "Names"
      path: "names"
      filename: "names.yaml"
      label-prefix: "N"
      images_per_row: 3
-
  name: "This map denotes the notable incidents and where they occurred on the voyage of discovery."
  shortname: "orellana_map"
  galleries:
    -
      name: "This map denotes the notable incidents and where they occurred on the voyage of discovery."
      shortname: "Map"
      path: "orellana_map"
      filename: "orellana_map.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "The Biography of Padre Gaspar de Carvahal, by Jos&eacute; Toribio Medina."
  shortname: "carvahal_medina"
  galleries:
    -
      name: "The Biography of Padre Gaspar de Carvahal, by Jos&eacute; Toribio Medina."
      shortname: "Carvahal Medina"
      path: "carvahal_medina"
      filename: "carvahal_medina.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "The Names of the River, by Jos&eacute; Toribio Medina."
  shortname: "river_medina"
  galleries:
    -
      name: "The Names of the River, by Jos&eacute; Toribio Medina."
      shortname: "River Medina"
      path: "river_medina"
      filename: "river_medina.yaml"
      label-prefix: "R"
      images_per_row: 3
-
  name: "Letter to the King by Gonzalo Pizarro about his attempt to find the Lands of Cinnamon and El Dorado."
  shortname: "cinnamon_pizarro"
  galleries:
    -
      name: "Letter to the King by Gonzalo Pizarro about his attempt to find the Lands of Cinnamon and El Dorado."
      shortname: "Cinnamon Pizarro"
      path: "cinnamon_pizarro"
      filename: "cinnamon_pizarro.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "This is the petition the companions asked the scrivener to draw up asking Orellana not to go back up the river to the Expeditionary force because of the swiftness of the river."
  shortname: "petition"
  galleries:
    -
      name: "This is the petition the companions asked the scrivener to draw up asking Orellana not to go back up the river to the Expeditionary force because of the swiftness of the river."
      shortname: "Cinnamon Pizarro"
      path: "petition"
      filename: "petition.yaml"
      label-prefix: "P"
      images_per_row: 3
